Repository Neul-pum/Gongganieum_FE, pull requests merged in 2024-06, with the labels that each got.

#9 Feat: 지도 페이지 건물 상세 정보 탭
  components/pages/map/DescriptionTab.tsx
  mock/popup.ts
  pages/map.tsx
  types/client.types.ts
Labels: ✨ feat

#12 Feat: 헤더 컴포넌트 (초기 버전)
  components/commons/Header.tsx
Labels: ✨ feat

#13 Feat: 슬라이더 컴포넌트
  components/pages/home/Slider.tsx
  package-lock.json
  package.json
Labels: ✨ feat

#15 Feat: 지도 페이지 탭 및 검색 기능 구현
  components/commons/Dropdown.tsx
  components/commons/SearchInput.tsx
  components/pages/map/BuildingCard.tsx
  components/pages/map/BuildingTab.tsx
  components/pages/map/DescriptionTab.tsx
  components/pages/map/PopupCard.tsx
  components/pages/map/RecommendTab.tsx
  components/pages/map/SearchTab.tsx
  components/pages/map/Tab.tsx
  constants/dropdown.ts
  hooks/useMapSearch.ts
  hooks/useOutsideClick.tsx
  mock/popup.ts
  pages/map.tsx
  types/client.types.ts
Labels: ✨ feat

#17 Feat: 지도 검색 결과를 상세 탭 및 강조핀으로 표시
  apis/api.ts
  apis/config/default.ts
  components/commons/Dropdown.tsx
  components/commons/SearchInput.tsx
  components/pages/map/BuildingCard.tsx
  components/pages/map/BuildingTab.tsx
  components/pages/map/PopupCard.tsx
  components/pages/map/RecommendTab.tsx
  components/pages/map/SearchTab.tsx
  components/pages/map/Tab.tsx
  constants/dropdown.ts
  hooks/map/useFetch.ts
  hooks/map/useInitMap.ts
  hooks/map/useMarkers.ts
  hooks/map/useSearch.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/map.tsx
  public/icons/dot.png
  store/index.ts
  store/slice/mapSlice.ts
  tailwind.config.ts
  types/client.types.ts
Labels: ✨ feat

#21 Feat: 문의하기 페이지
  components/commons/ConsentCheckbox.tsx
  components/commons/Dropdown.tsx
  components/commons/Input.tsx
  components/commons/SearchInput.tsx
  components/pages/map/BuildingCard.tsx
  components/pages/map/BuildingTab.tsx
  components/pages/map/PopupCard.tsx
  components/pages/map/RecommendTab.tsx
  components/pages/map/SearchTab.tsx
  hooks/map/useFetch.ts
  hooks/useKakaoMap.ts
  package-lock.json
  package.json
  pages/contact.tsx
  pages/map.tsx
Labels: ✨ feat

#19 Feat: 프로필 컴포넌트
  components/pages/mypage/Profile.tsx
Labels: ✨ feat

#22 ⚡️Fix: 카카오 지도 로딩 오류 수정
  hooks/map/useInitMap.ts
  hooks/useKakaoMap.ts
Labels: ⚡️ fix

#25 Chore: design system
  components/pages/map/BuildingCard.tsx
  components/pages/map/BuildingTab.tsx
  hooks/map/useInitMap.ts
  hooks/map/useMarkers.ts
  hooks/useKakaoMap.ts
  pages/_app.tsx
  public/fonts/pretendard/Pretendard-Bold.subset.woff2
  public/fonts/pretendard/Pretendard-ExtraBold.subset.woff2
  public/fonts/pretendard/Pretendard-Medium.subset.woff2
  public/fonts/pretendard/Pretendard-Regular.subset.woff2
  public/fonts/pretendard/Pretendard-SemiBold.subset.woff2
  public/fonts/pretendard/font.css
  styles/globals.css
  tailwind.config.ts
Labels: 🩹 chore

#24 Feat: 로그인 페이지
  components/pages/login/LoginBox.tsx
  components/pages/login/LoginButton.tsx
  pages/login.tsx
  public/icons/index.ts
  public/icons/kakao-logo.svg
  public/icons/naver-logo.svg
  public/images/login-background-image.png
  styles/globals.css
  tailwind.config.ts
Labels: 💄 design

#29 Design: 지도 페이지 탭 디자인 구현
  components/commons/Dropdown.tsx
  components/commons/SearchInput.tsx
  components/commons/Tag.tsx
  components/pages/map/BuildingCard.tsx
  components/pages/map/RecommendTab.tsx
  components/pages/map/SearchTab.tsx
  components/pages/map/Tab.tsx
  hooks/map/useMarkers.ts
  public/icons/arrow-down.svg
  public/icons/art.svg
  public/icons/beauty.svg
  public/icons/building.svg
  public/icons/character.svg
  public/icons/entertainment.svg
  public/icons/etc.svg
  public/icons/fashion.svg
  public/icons/finance.svg
  public/icons/flag.svg
  public/icons/food.svg
  public/icons/game.svg
  public/icons/index.ts
  public/icons/it.svg
  public/icons/search.svg
  public/images/mock-building-image.jpg
  styles/globals.css
  tailwind.config.ts
  types/client.types.ts
Labels: 💄 design

#31 Feat: 레이아웃 구현
  components/commons/Footer.tsx
  components/commons/Header.tsx
  components/commons/Layout.tsx
  components/commons/Provider.tsx
  components/commons/SearchInput.tsx
  components/commons/Tag.tsx
  components/pages/map/BuildingCard.tsx
  components/pages/map/Tab.tsx
  pages/_app.tsx
  pages/map.tsx
  public/icons/index.ts
  public/icons/logo.svg
Labels: ✨ feat

#33 Feat: 모달 추가
  components/commons/Button.tsx
  components/commons/Input.tsx
  components/commons/PortalModal.tsx
  components/modals/ProfileModal.tsx
  components/modals/WelcomeModal.tsx
  pages/_document.tsx
  public/icons/circulation.svg
  public/icons/index.ts
  public/images/welcome-modal-image.png
  utils/generateRandomNickname.ts
Labels: ✨ feat, 💄 design
