Repository Neul-pum/Gongganieum_FE, pull requests merged in 2024-07, with the labels that each got.

#36 Feat: 빌딩 상세 탭 기능 구현 및 api 연결
  apis/getBuildingData.ts
  apis/getPopulationData.ts
  components/commons/ImageLayout.tsx
  components/commons/Tag.tsx
  components/commons/description/AgeRatioCard.tsx
  components/commons/description/BuildingInfoCard.tsx
  components/commons/description/CongestionCard.tsx
  components/commons/description/Description.tsx
  components/commons/description/DescriptionCard.tsx
  components/commons/description/GenderRatioCard.tsx
  components/commons/description/MapCard.tsx
  components/commons/description/PopupHistoryCard.tsx
  components/commons/description/PopupRankingCard.tsx
  components/commons/description/ResidentRatioCard.tsx
  components/pages/map/BuildingCard.tsx
  components/pages/map/BuildingTab.tsx
  components/pages/map/Tab.tsx
  constants/common.tsx
  constants/dropdown.ts
  constants/populationDataFilter.ts
  constants/regions.ts
  hooks/map/useFetch.ts
  hooks/map/useSearch.ts
  package-lock.json
  package.json
  pages/population.tsx
  public/icons/arrow-back.svg
  public/icons/art.svg
  public/icons/building-pin.svg
  public/icons/finance.svg
  public/icons/game.svg
  public/icons/index.ts
  public/icons/it.svg
  public/icons/marker.svg
  types/client.types.ts
  utils/populationDataSpliter.ts
  utils/populationDataSplitter.ts
Labels: ✨ feat

#34 Feat: 리스트 페이지
  apis/api.ts
  components/commons/Header.tsx
  components/commons/Tag.tsx
  components/commons/description/PopupRankingCard.tsx
  components/pages/list/ListBuildingCard.tsx
  components/pages/list/ListCategoryTabs.tsx
  components/pages/list/ListCheckBoxs.tsx
  components/pages/list/ListSortingButton.tsx
  components/pages/map/RecommendTab.tsx
  components/pages/map/Tab.tsx
  hooks/map/useFetch.ts
  hooks/map/useSearch.ts
  pages/list.tsx
  public/icons/black-check.svg
  public/icons/blank-like.svg
  public/icons/index.ts
  public/icons/red-like.svg
  public/images/mock-building-image2.jpg
  types/client.types.ts
Labels: ✨ feat, 💄 design

#39 Feat: 빌딩 상세 페이지
  apis/getBuildingData.ts
  components/commons/BuildingTitle.tsx
  components/commons/ImageLayout.tsx
  components/commons/description/BuildingInfoCard.tsx
  components/commons/description/Description.tsx
  components/commons/description/DescriptionCard.tsx
  components/commons/description/MapCard.tsx
  components/commons/description/PopupRankingCard.tsx
  components/pages/list/ListBuildingCard.tsx
  components/pages/map/BuildingCard.tsx
  components/pages/map/BuildingTab.tsx
  constants/common.tsx
  hooks/useBuildingImageUrls.ts
  pages/list/[id]/index.tsx
  pages/list/index.tsx
  public/images/no-image.jpg
Labels: ✨ feat

#41 Feat: 이미지 프리뷰
  components/commons/ImageLayout.tsx
  components/commons/ImagePreview.tsx
  pages/list/[id]/index.tsx
  public/icons/arrow-left.svg
  public/icons/arrow-right.svg
  public/icons/close.svg
  public/icons/index.ts
Labels: ✨ feat

#42 Feat: 홈페이지
  components/commons/ImagePreview.tsx
  components/pages/home/HomeBanner.tsx
  components/pages/home/HomeBuildingCard.tsx
  components/pages/home/HomeCardSlider.tsx
  components/pages/home/HomeEditorRecommend.tsx
  components/pages/home/HomeMagazineCard.tsx
  components/pages/home/HomeMagazineSlider.tsx
  components/pages/home/HomeSliderWithPagination.tsx
  components/pages/home/Slider.tsx
  pages/_app.tsx
  pages/index.tsx
  public/icons/arrow-left.svg
  public/icons/arrow-next-button.svg
  public/icons/arrow-prev-button.svg
  public/icons/arrow-right.svg
  public/icons/index.ts
  public/icons/white-marker.svg
  public/images/home-banner-background.png
  public/images/home-editor-recommend-image.png
  styles/styles.css
Labels: ✨ feat, 💄 design

#44 Feat: 소셜로그인 및 회원가입
  apis/auth.ts
  apis/config/default.ts
  components/commons/Button.tsx
  components/commons/Input.tsx
  components/commons/PortalModal.tsx
  components/modals/ProfileModal.tsx
  components/modals/WelcomeModal.tsx
  components/pages/login/LoginBox.tsx
  components/pages/login/LoginButton.tsx
  hooks/useManageAccessToken.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/oauth/[provider].tsx
Labels: ✨ feat

#46 Design: 반응형 디자인 추가 (홈페이지 / 리스트페이지)
  components/commons/Footer.tsx
  components/commons/Header.tsx
  components/commons/PortalModal.tsx
  components/commons/SearchInput.tsx
  components/pages/home/HomeBanner.tsx
  components/pages/home/HomeBuildingCard.tsx
  components/pages/home/HomeCardSlider.tsx
  components/pages/home/HomeEditorRecommend.tsx
  components/pages/home/HomeMagazineCard.tsx
  components/pages/home/HomeMagazineSlider.tsx
  components/pages/home/HomeMobileBuildingCardSlider.tsx
  components/pages/home/HomeMobileMagazineSlider.tsx
  components/pages/home/HomeSliderWithPagination.tsx
  components/pages/list/ListBuildingCard.tsx
  components/pages/list/ListCategoryTabs.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/list/index.tsx
  public/icons/hamburger-menu.svg
  public/icons/index.ts
  public/icons/logo.svg
  styles/styles.css
  tailwind.config.ts
Labels: 💄 design

#51 Fix: 공공 데이터 주소 변경
  apis/getPopulationData.ts
Labels: ⚡️ fix

#52 Design: 상세 페이지 모바일 디자인
  components/commons/BuildingTitle.tsx
  components/commons/Header.tsx
  components/commons/ImageLayout.tsx
  components/commons/ImagePreview.tsx
  components/commons/PortalImagePreview.tsx
  components/commons/description/BuildingInfoCard.tsx
  components/commons/description/Description.tsx
  components/commons/description/DescriptionCard.tsx
  components/commons/description/MapCard.tsx
  hooks/useBuildingImageUrls.ts
  package-lock.json
  pages/_document.tsx
  pages/list/[id]/index.tsx
Labels: 💄 design

#53 Feat: 관리자 페이지
  components/pages/admin/ImgInput.tsx
  package-lock.json
  package.json
  pages/admin.tsx
  public/images/add-image.png
Labels: ✨ feat

#54 Fix: Admin 페이지 건물 검색 방법 변경
  pages/admin.tsx
Labels: ⚡️ fix, ♻️ refactor

#61 Feat: 지도 페이지 바텀시트
  apis/api.ts
  components/commons/BottomSheet.tsx
  components/commons/BuildingTitle.tsx
  components/commons/ImageLayout.tsx
  components/commons/ImagePreview.tsx
  components/commons/SearchInput.tsx
  components/commons/description/Description.tsx
  components/pages/contact/Banner.tsx
  components/pages/contact/steps/EtcStep.tsx
  components/pages/contact/steps/PersonalInfoStep.tsx
  components/pages/contact/steps/UsageInfoStep.tsx
  components/pages/map/BuildingTab.tsx
  components/pages/map/FilterButton.tsx
  components/pages/map/IsOursButton.tsx
  components/pages/map/LikedButton.tsx
  components/pages/map/RecommendTab.tsx
  components/pages/map/SearchTab.tsx
  components/pages/map/Tab.tsx
  constants/regions.ts
  hooks/useBottomSheet.tsx
  pages/contact/[id]/index.tsx
  pages/map.tsx
  public/icons/heart.svg
  public/icons/index.ts
  public/icons/selected-pin.svg
  public/icons/star.svg
Labels: ✨ feat

#62 Fix: 토큰 및 유저 정보 관리
  apis/auth.ts
  components/commons/BuildingCard.tsx
  components/commons/Header.tsx
  components/commons/modals/ProfileEditModal.tsx
  components/commons/modals/ProfileModal.tsx
  components/commons/modals/WelcomeModal.tsx
  hooks/useManageAccessToken.ts
  hooks/useSession.ts
  pages/index.tsx
  pages/mypage.tsx
  pages/oauth/[provider].tsx
  store/index.ts
  store/slice/userSlice.ts
  types/client.types.ts
Labels: ⚡️ fix

#63 Feat: 홈페이지 데이터 연동 및 QA 디자인 수정
  apis/api.ts
  components/commons/BuildingCard.tsx
  components/commons/modals/ProfileEditModal.tsx
  components/pages/home/HomeCardSlider.tsx
  components/pages/home/HomeEditorRecommend.tsx
  components/pages/home/HomeMobileBuildingCardSlider.tsx
  components/pages/home/HomeMobileMagazineSlider.tsx
  components/pages/home/HomeSliderWithPagination.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/mypage.tsx
  types/client.types.ts
Labels: ✨ feat, 💄 design

#68 Design: 디자인 추가
  components/commons/BuildingCard.tsx
  components/commons/PortalModal.tsx
  components/commons/modals/ProfileEditModal.tsx
  components/commons/modals/ProfileModal.tsx
  components/commons/modals/WelcomeModal.tsx
  components/pages/login/LoginBox.tsx
  components/pages/login/LoginButton.tsx
  components/pages/map/RecommendTab.tsx
  components/pages/map/SearchTab.tsx
  constants/common.tsx
  pages/404.tsx
  pages/list/index.tsx
  pages/login.tsx
  public/images/404.png
  public/images/listpage-empty-cart.png
  public/images/no-image.jpg
  public/images/no-image.png
Labels: 💄 design

#69 Fix: 문의하기 항목 추가 및 로그인 로직 수정
  apis/api.ts
  apis/auth.ts
  components/commons/Dropdown.tsx
  components/commons/Header.tsx
  components/commons/Input.tsx
  components/commons/modals/ProfileModal.tsx
  components/pages/contact/ContactFunnel.tsx
  components/pages/contact/FunnelTitle.tsx
  components/pages/contact/steps/EtcStep.tsx
  components/pages/contact/steps/PersonalInfoStep.tsx
  components/pages/contact/steps/UsageInfoStep.tsx
  components/pages/list/[id]/ContactBox.tsx
  components/pages/map/RecommendTab.tsx
  hooks/useSession.ts
  pages/contact/[id]/index.tsx
  pages/oauth/[provider].tsx
  types/client.types.ts
Labels: ⚡️ fix

#71 Doc: 프로젝트 소개 추가
  README.md
Labels: 🩹 chore

#73 Feat: 리스트 페이지 페이지네이션 구현
  apis/api.ts
  components/commons/Header.tsx
  components/commons/SearchInput.tsx
  components/pages/list/ListCheckBoxs.tsx
  components/pages/list/PageButton.tsx
  components/pages/map/FilterButton.tsx
  components/pages/map/IsOursButton.tsx
  components/pages/map/SearchTab.tsx
  components/pages/map/Tab.tsx
  hooks/useFetch.ts
  hooks/useSearch.ts
  pages/list/index.tsx
Labels: ✨ feat

#75 Design: 매거진 페이지 디자인 추가
  components/pages/magazine/MagazineBanner.tsx
  components/pages/magazine/MagazineCategory.tsx
  components/pages/magazine/MagazineGridList.tsx
  components/pages/magazine/MagazineListWithBackground.tsx
  components/pages/magazine/MagazineMainBanner.tsx
  components/pages/magazine/MagazineSlideList.tsx
  pages/index.tsx
  pages/magazine/[id]/index.tsx
  pages/magazine/index.tsx
  public/images/magazine/magazine-architecture-2.jpg
  public/images/magazine/magazine-architecture-3.jpg
  public/images/magazine/magazine-architecture.jpg
  public/images/magazine/magazine-glass-building.jpg
  public/images/magazine/main-banner.jpg
  public/images/magazine/mock-son.webp
  public/images/magazine/popup_1.jpg
  public/images/magazine/popup_2.jpg
  public/images/magazine/popup_3.jpg
  public/images/magazine/popup_4.jpg
  public/images/magazine/popup_5.jpg
  public/images/magazine/덱스.jpg
  public/images/magazine/민지.jpg
  public/images/magazine/민지2.jpg
  public/images/magazine/민지3.webp
  public/images/magazine/민지4.webp
  public/images/magazine/민지5.webp
  public/images/magazine/아이린.jpeg
Labels: 💄 design

#79 Feat: 메타태그
  components/commons/Header.tsx
  components/commons/MetaTag.tsx
  mock/popup.ts
  pages/404.tsx
  pages/_document.tsx
  pages/admin.tsx
  pages/contact/[id]/index.tsx
  pages/contact/index.tsx
  pages/index.tsx
  pages/list/[id]/index.tsx
  pages/list/index.tsx
  pages/login.tsx
  pages/magazine/[id]/index.tsx
  pages/magazine/index.tsx
  pages/map.tsx
  pages/mypage.tsx
  public/icons/xs-logo.svg
Labels: ✨ feat

#80 Fix: 지도 마커 중복 현상 수정
  hooks/map/useInitMap.tsx
Labels: ⚡️ fix

#83 Fix: 레이아웃 깜빡임 수정
  components/commons/ImageLayout.tsx
  components/pages/home/HomeMobileBuildingCardSlider.tsx
  components/pages/home/HomeMobileMagazineSlider.tsx
  components/pages/home/HomeSliderWithPagination.tsx
  components/pages/list/ListCategoryTabs.tsx
  components/pages/login/LoginBox.tsx
  pages/list/index.tsx
Labels: ⚡️ fix

#84 Release: 2차 배포
  .eslintrc.json
  README.md
  apis/auth.ts
  components/commons/ConsentCheckbox.tsx
  components/commons/Header.tsx
  components/commons/ImageLayout.tsx
  components/commons/MetaTag.tsx
  components/commons/PersonalInfoPolicy.tsx
  components/commons/PrivacyPolicy.tsx
  components/commons/TermsAndConditions.tsx
  components/commons/modals/PersonalInfoPolicyModal.tsx
  components/commons/modals/TermsModal.tsx
  components/pages/home/HomeMobileBuildingCardSlider.tsx
  components/pages/home/HomeMobileMagazineSlider.tsx
  components/pages/home/HomeSliderWithPagination.tsx
  components/pages/list/ListCategoryTabs.tsx
  components/pages/login/LoginBox.tsx
  components/pages/map/BuildingTab.tsx
  constants/common.tsx
  pages/list/index.tsx
  public/icons/black-check-large.svg
Labels: 🩹 chore
