Repository Neul-pum/Gongganieum_FE, pull requests merged in 2024-08, with the labels that each got.

#90 Feat: 내 문의 내역
  apis/api.ts
  components/commons/BuildingTitle.tsx
  components/commons/ImagePreview.tsx
  components/commons/description/PopupHistoryCard.tsx
  components/commons/modals/MyContactModal.tsx
  components/commons/modals/PersonalInfoPolicyModal.tsx
  components/commons/modals/TermsModal.tsx
  components/commons/policy/PersonalInfoPolicy.tsx
  components/commons/policy/PrivacyPolicy.tsx
  components/commons/policy/TermsAndConditions.tsx
  components/pages/contact/DateInput.tsx
  components/pages/contact/steps/EtcStep.tsx
  components/pages/contact/steps/PersonalInfoStep.tsx
  components/pages/list/[id]/ContactBox.tsx
  components/pages/map/BuildingTab.tsx
  components/pages/map/ContactBox.tsx
  components/pages/map/LikedButton.tsx
  components/pages/mypage/ContactTab.tsx
  components/pages/mypage/LikeBuildingTab.tsx
  components/pages/mypage/MyContact.tsx
  hooks/map/useInitMap.tsx
  hooks/usePreserveScroll.tsx
  hooks/usePreventScroll.tsx
  pages/contact/[id]/index.tsx
  pages/index.tsx
  pages/list/[id]/index.tsx
  pages/map.tsx
  pages/mypage.tsx
  styles/styles.css
  types/client.types.ts
Labels: ✨ feat

#91 Release: 4차 배포
  apis/api.ts
  components/commons/BuildingTitle.tsx
  components/commons/ImagePreview.tsx
  components/commons/description/PopupHistoryCard.tsx
  components/commons/modals/MyContactModal.tsx
  components/commons/modals/PersonalInfoPolicyModal.tsx
  components/commons/modals/TermsModal.tsx
  components/commons/policy/PersonalInfoPolicy.tsx
  components/commons/policy/PrivacyPolicy.tsx
  components/commons/policy/TermsAndConditions.tsx
  components/pages/contact/DateInput.tsx
  components/pages/contact/steps/EtcStep.tsx
  components/pages/contact/steps/PersonalInfoStep.tsx
  components/pages/list/[id]/ContactBox.tsx
  components/pages/map/BuildingTab.tsx
  components/pages/map/ContactBox.tsx
  components/pages/map/LikedButton.tsx
  components/pages/mypage/ContactTab.tsx
  components/pages/mypage/LikeBuildingTab.tsx
  components/pages/mypage/MyContact.tsx
  hooks/map/useInitMap.tsx
  hooks/usePreserveScroll.tsx
  hooks/usePreventScroll.tsx
  pages/contact/[id]/index.tsx
  pages/index.tsx
  pages/list/[id]/index.tsx
  pages/map.tsx
  pages/mypage.tsx
  styles/styles.css
  types/client.types.ts
Labels: 🩹 chore

#92 Feat: 매거진 에디터 이미지 기능 추가 및 매거진 API 연결
  apis/api.ts
  components/commons/BuildingTitle.tsx
  components/commons/modals/ProfileModal.tsx
  components/pages/home/HomeMagazineSlider.tsx
  components/pages/home/HomeMobileMagazineSlider.tsx
  components/pages/magazine/MagazineCategory.tsx
  components/pages/magazine/MagazineGridList.tsx
  components/pages/magazine/MagazineListWithBackground.tsx
  components/pages/magazine/MagazineMainBanner.tsx
  components/pages/magazine/MagazinePeopleList.tsx
  components/pages/magazine/MagazinePopupList.tsx
  components/pages/magazine/MagazineSlideList.tsx
  components/pages/magazine/MagazineSpaceList.tsx
  package-lock.json
  package.json
  pages/editor.tsx
  pages/list/index.tsx
  pages/magazine/[id]/index.tsx
  pages/magazine/index.tsx
  types/client.types.ts
Labels: ✨ feat

#95 Release: 5차 배포
  apis/api.ts
  components/commons/BuildingTitle.tsx
  components/commons/modals/ProfileModal.tsx
  components/pages/admin/contents/ShowBuildings.tsx
  components/pages/admin/contents/ShowCarousels.tsx
  components/pages/admin/contents/ShowContacts.tsx
  components/pages/admin/contents/ShowUsers.tsx
  components/pages/home/HomeMagazineCard.tsx
  components/pages/home/HomeMagazineSlider.tsx
  components/pages/home/HomeMobileMagazineSlider.tsx
  components/pages/magazine/MagazineCategory.tsx
  components/pages/magazine/MagazineGridList.tsx
  components/pages/magazine/MagazineListWithBackground.tsx
  components/pages/magazine/MagazineMainBanner.tsx
  components/pages/magazine/MagazinePeopleList.tsx
  components/pages/magazine/MagazinePopupList.tsx
  components/pages/magazine/MagazineSlideList.tsx
  components/pages/magazine/MagazineSpaceList.tsx
  components/pages/mypage/MyContact.tsx
  constants/admin ContentTableHeader.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/editor.tsx
  pages/list/index.tsx
  pages/magazine/[id]/index.tsx
  pages/magazine/index.tsx
  pages/mypage.tsx
  public/images/magazine/magazine-architecture-2.jpg
  public/images/magazine/magazine-architecture-3.jpg
  public/images/magazine/magazine-architecture.jpg
  public/images/magazine/mock-son.webp
  public/images/magazine/popup_1.jpg
  public/images/magazine/popup_2.jpg
  public/images/magazine/popup_3.jpg
  public/images/magazine/popup_4.jpg
  public/images/magazine/popup_5.jpg
  public/images/magazine/덱스.jpg
  public/images/magazine/민지.jpg
  public/images/magazine/민지2.jpg
  public/images/magazine/민지3.webp
  public/images/magazine/민지4.webp
  public/images/magazine/민지5.webp
  public/images/magazine/아이린.jpeg
  types/client.types.ts
Labels: 🩹 chore

#96 Fix: 직영 건물 필터 중 핀 클릭 시 필터 해제되는 오류 수정
  components/pages/map/BuildingCard.tsx
  hooks/map/useInitMap.tsx
  hooks/map/useLikedMarkers.tsx
  hooks/map/useMarkers.ts
  utils/getIsDefaultMarkersVisible.ts
Labels: ⚡️ fix

#97 Release: 6차 배포
  components/pages/map/BuildingCard.tsx
  hooks/map/useInitMap.tsx
  hooks/map/useLikedMarkers.tsx
  hooks/map/useMarkers.ts
  utils/getIsDefaultMarkersVisible.ts
Labels: 🩹 chore

#98 Refactor: 관리자 페이지 기능 추가 및 3d 공간투어 기능 적용
  apis/admin.ts
  apis/api.ts
  components/commons/Header.tsx
  components/pages/admin/TextInput.tsx
  components/pages/admin/contents/BuildingCU.tsx
  components/pages/admin/contents/BuildingRD.tsx
  components/pages/admin/contents/CarouselCU.tsx
  components/pages/admin/contents/CarouselRD.tsx
  components/pages/admin/contents/ContactRD.tsx
  components/pages/admin/contents/CreateBuilding.tsx
  components/pages/admin/contents/PopupCreate.tsx
  components/pages/admin/contents/ShowBuildings.tsx
  components/pages/admin/contents/UserRD.tsx
  components/pages/home/HomeCardSlider.tsx
  components/pages/home/HomeMobileBuildingCardSlider.tsx
  components/pages/list/[id]/ContactBox.tsx
  components/pages/map/ContactBox.tsx
  components/pages/map/LikedButton.tsx
  constants/adminContentTableHeader.ts
  hooks/useHandleServerReq.ts
  package-lock.json
  package.json
  pages/admin/[content].tsx
  pages/admin/index.tsx
  pages/editor.tsx
  pages/list/[id]/index.tsx
  pages/login.tsx
  pages/mypage.tsx
  public/icons/close-btn.svg
  public/icons/index.ts
  public/images/3d-room-tour.png
  types/client.types.ts
Labels: ✨ feat, ♻️ refactor

#99 Release: 7차 배포
  apis/admin.ts
  apis/api.ts
  components/commons/Header.tsx
  components/pages/admin/TextInput.tsx
  components/pages/admin/contents/BuildingCU.tsx
  components/pages/admin/contents/BuildingRD.tsx
  components/pages/admin/contents/CarouselCU.tsx
  components/pages/admin/contents/CarouselRD.tsx
  components/pages/admin/contents/ContactRD.tsx
  components/pages/admin/contents/CreateBuilding.tsx
  components/pages/admin/contents/PopupCreate.tsx
  components/pages/admin/contents/ShowBuildings.tsx
  components/pages/admin/contents/UserRD.tsx
  components/pages/home/HomeCardSlider.tsx
  components/pages/home/HomeMobileBuildingCardSlider.tsx
  components/pages/list/[id]/ContactBox.tsx
  components/pages/map/ContactBox.tsx
  components/pages/map/LikedButton.tsx
  constants/adminContentTableHeader.ts
  hooks/useHandleServerReq.ts
  package-lock.json
  package.json
  pages/admin/[content].tsx
  pages/admin/index.tsx
  pages/editor.tsx
  pages/list/[id]/index.tsx
  pages/login.tsx
  pages/mypage.tsx
  public/icons/close-btn.svg
  public/icons/index.ts
  public/images/3d-room-tour.png
  types/client.types.ts
Labels: 🩹 chore
